### ISSUE TITLE
Any way to integrate braintree with firebase or do i need to have a server setup for payments?

### ISSUE THREAD

**Issue by shafayatb** [braintree/braintree-ios-drop-in#88]
Hi,

I have app made with firebase as the server side. I am wondering how can I setup braintree with firebase.

Thank you.

**Comment by crookedneighbor** [comment]
You may able to install the Braintree node sdk on your firebase application. See https://stackoverflow.com/questions/47898059/integrate-cloud-functions-for-firebase-with-braintree

You will want to, of course, ensure that your API keys are secure in Firebase so they are not leaked.

Since this is not a problem with the SDK, I'm going to close it. Please contact our support team if you need additional help https://articles.braintreepayments.com/forms/contact

**Comment by shafayatb** [comment]
@crookedneighbor I have integrated the node sdk on my firebase app and deployed the function. But when i make a request to the function it gives me this exception( found from the firebase log console),

```
{ unexpectedError: Unexpected request error: Error: getaddrinfo ENOTFOUND api.sandbox.braintreegateway.com api.sandbox.braintreegateway.com:443
    at Object.UnexpectedError (/user_code/node_modules/braintree/lib/braintree/exceptions.js:7:15)
    at ClientRequest.theRequest.on.err (/user_code/node_modules/braintree/lib/braintree/http.js:159:32)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) name: 'unexpectedError', type: 'unexpectedError' }
```
I am new to node and i didn't find any solutions to this from google. Is this an ask issue or a firebase issue?

**Comment by crookedneighbor** [comment]
Seems like firebase blocking the request to me. I noticed that services like Zapier have connections between firebase and Braintree https://zapier.com/apps/braintree/integrations/firebase

May be useful for what you need to do.

**Comment by shafayatb** [comment]
@kondasoft  I asked the client to buy the flame plan for firebase and I got Braintree to work. But my app got rejected from the app store as apple only accept their in app purchase for the digital goods. So all that effort for nothing. :(

**Comment by ducpt2** [comment]
@shafayatb so we only can use in-app purchase to buy something in app? 
Thanks.

**Comment by 3amoura** [comment]
@shafayatb is right, But on the contrary, Apple doesn't support In-App purchase for Real goods

**Comment by nikoswsn** [comment]
My firebase function works when tested locally but when I deploy I get the following error. Can you please confirm that this is due to the free plan I'm using on Firebase? 
`{ unexpectedError: Unexpected request error: Error: getaddrinfo EAI_AGAIN api.sandbox.braintreegateway.com:443
    at Object.UnexpectedError (/srv/node_modules/braintree/lib/braintree/exceptions.js:7:15)
    at ClientRequest.theRequest.on.err (/srv/node_modules/braintree/lib/braintree/http.js:168:32)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) name: 'unexpectedError', type: 'unexpectedError' }`

**Comment by sestevens** [comment]
Hi @nikoswsn. This doesn't sound like something we'll be able to help troubleshoot from the Braintree side. I would suggest reaching out to Firebase support for assistance.

**Comment by iovanom** [comment]
I had the same problem. @nikoswsn you need to use a non-free plan because the firebase free plan is not allowed to make an external requests.

**Comment by ivanjeremic** [comment]
The Stripe team has made a Firebase extension to easily integrate Stripe subscription payments, can the braintree team do the same and create a firebase extension?
